### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Prog-LucasAlves** [numba/llvmlite#800] opened 2021-11-28 03:35 UTC
## Reporting a bug
Running setup.py install for llvmlite ... error

- [x] I have tried using the latest released version of llvmlite (most recent is
 visible in the change log (https://github.com/numba/llvmlite/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by esc** [comment] 2021-11-28 10:04
> ## Reporting a bug
> Running setup.py install for llvmlite ... error
> 
> * [x]  I have tried using the latest released version of llvmlite (most recent is
>   visible in the change log (https://github.com/numba/llvmlite/blob/master/CHANGE_LOG).
> * [x]  I have included a self contained code sample to reproduce the problem.
>   i.e. it's possible to run as 'python bug.py'.

@Prog-LucasAlves thank you for reporting this. Unfortunately there is not enough information in the report to diagnose what may have gone wrong. Please submit the full log of the commands you entered and the output that was given including all error messages so that we can take a closer look. Thank you!

**Comment by Prog-LucasAlves** [comment] 2021-11-28 18:24
![Captura de tela 2021-11-28 152414](https://user-images.githubusercontent.com/68572723/143780983-4ebd9004-7cca-40c9-9926-93a50a05bfd8.png)

**Comment by esc** [comment] 2021-11-28 19:32
> ![Captura de tela 2021-11-28 152414](https://user-images.githubusercontent.com/68572723/143780983-4ebd9004-7cca-40c9-9926-93a50a05bfd8.png)

Oh yes, I can spot what happened. You tried to install llvmlite version `0.2.0`. This version is about 6 years old and no longer supported. You can try to install the latest version using:

```
pip install llvmlite
```

Good luck and let us know if this fixes your issue, thank you!

**Comment by Prog-LucasAlves** [comment] 2021-11-28 19:59
> 

![Captura de tela 2021-11-28 165807](https://user-images.githubusercontent.com/68572723/143783908-2317b004-6e9c-48c8-be40-6149ba7c9b8d.png)

**Comment by esc** [comment] 2021-11-28 20:29
> > 
> 
> ![Captura de tela 2021-11-28 165807](https://user-images.githubusercontent.com/68572723/143783908-2317b004-6e9c-48c8-be40-6149ba7c9b8d.png)

@Prog-LucasAlves thank you for reporting back. It seems like there is a cached version of `llvmlite` present in your current Python installation. I would recommend to try:

```
pip --no-cache-dir install llvmlite
```

Hope this helps. Note that, if this does not help, please do select and copy and paste the entire output of the command. Rather than making a screenshot, because with a screenshot, half the message is missing. Thank you!

**Comment by Prog-LucasAlves** [comment] 2021-11-28 23:57
(.venv) PS D:\Prjts\dados_financeiros_b3> pip --no-cache-dir install llvmlite
Collecting llvmlite
  Downloading llvmlite-0.35.0.tar.gz (121 kB)
     |████████████████████████████████| 121 kB 6.4 MB/s
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for llvmlite, since package 'wheel' is not installed.
Installing collected packages: llvmlite
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\Prjts\dados_financeiros_b3\.venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Lucas\\AppData\\Local\\Temp\\pip-install-4c43yoe8\\llvmlite_bb5933e9340d43069eebd16b8e54d93e\\setup.py'"'"'; __file__='"'"'C:\\Users\\Lucas\\AppData\\Local\\Temp\\pip-install-4c43yoe8\\llvmlite_bb5933e9340d43069eebd16b8e54d93e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Lucas\AppData\Local\Temp\pip-record-r4ds_r_3\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Prjts\dados_financeiros_b3\.venv\include\site\python3.10\llvmlite'
         cwd: C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\
    Complete output (29 lines):
    running install
    D:\Prjts\dados_financeiros_b3\.venv\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    got version from file C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\llvmlite/_version.py {'version': '0.35.0', 'full': 'ea23b026930cc00824c907172383f54c9d438e6b'}
    running build_ext
    D:\Prjts\dados_financeiros_b3\.venv\Scripts\python.exe C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\ffi\build.py
    Trying generator 'Visual Studio 15 2017 Win64'
    Traceback (most recent call last):
      File "C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\ffi\build.py", line 191, in <module>
        main()
      File "C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\ffi\build.py", line 179, in main    
        main_win32()
      File "C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\ffi\build.py", line 88, in main_win32
        generator = find_win32_generator()
      File "C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\ffi\build.py", line 76, in find_win32_generator
        try_cmake(cmake_dir, build_dir, generator)
      File "C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\ffi\build.py", line 28, in try_cmake
        subprocess.check_call(['cmake', '-G', generator, cmake_dir])
      File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 364, in check_call
        retcode = call(*popenargs, **kwargs)
      File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado
    error: command 'D:\\Prjts\\dados_financeiros_b3\\.venv\\Scripts\\python.exe' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\Prjts\dados_financeiros_b3\.venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Lucas\\AppData\\Local\\Temp\\pip-install-4c43yoe8\\llvmlite_bb5933e9340d43069eebd16b8e54d93e\\setup.py'"'"'; __file__='"'"'C:\\Users\\Lucas\\AppData\\Local\\Temp\\pip-install-4c43yoe8\\llvmlite_bb5933e9340d43069eebd16b8e54d93e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Lucas\AppData\Local\Temp\pip-record-r4ds_r_3\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Prjts\dados_financeiros_b3\.venv\include\site\python3.10\llvmlite' Check the logs for full command output.

**Comment by esc** [comment] 2021-11-29 07:10
> (.venv) PS D:\Prjts\dados_financeiros_b3> pip --no-cache-dir install llvmlite Collecting llvmlite Downloading llvmlite-0.35.0.tar.gz (121 kB) |████████████████████████████████| 121 kB 6.4 MB/s Preparing metadata (setup.py) ... done Using legacy 'setup.py install' for llvmlite, since package 'wheel' is not installed. Installing collected packages: llvmlite Running setup.py install for llvmlite ... error ERROR: Command errored out with exit status 1: command: 'D:\Prjts\dados_financeiros_b3.venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\setup.py'"'"'; **file**='"'"'C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(**file**) if os.path.exists(**file**) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\Lucas\AppData\Local\Temp\pip-record-r4ds_r_3\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Prjts\dados_financeiros_b3.venv\include\site\python3.10\llvmlite' cwd: C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e Complete output (29 lines): running install D:\Prjts\dados_financeiros_b3.venv\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools. warnings.warn( running build got version from file C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\llvmlite/_version.py {'version': '0.35.0', 'full': 'ea23b026930cc00824c907172383f54c9d438e6b'} running build_ext D:\Prjts\dados_financeiros_b3.venv\Scripts\python.exe C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\ffi\build.py Trying generator 'Visual Studio 15 2017 Win64' Traceback (most recent call last): File "C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\ffi\build.py", line 191, in main() File "C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\ffi\build.py", line 179, in main main_win32() File "C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\ffi\build.py", line 88, in main_win32 generator = find_win32_generator() File "C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\ffi\build.py", line 76, in find_win32_generator try_cmake(cmake_dir, build_dir, generator) File "C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\ffi\build.py", line 28, in try_cmake subprocess.check_call(['cmake', '-G', generator, cmake_dir]) File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 364, in check_call retcode = call(*popenargs, **kwargs) File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call with Popen(*popenargs, **kwargs) as p: File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "C:\Users\Lucas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado error: command 'D:\Prjts\dados_financeiros_b3\.venv\Scripts\python.exe' failed with exit code 1 ---------------------------------------- ERROR: Command errored out with exit status 1: 'D:\Prjts\dados_financeiros_b3.venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\setup.py'"'"'; **file**='"'"'C:\Users\Lucas\AppData\Local\Temp\pip-install-4c43yoe8\llvmlite_bb5933e9340d43069eebd16b8e54d93e\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(**file**) if os.path.exists(**file**) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\Lucas\AppData\Local\Temp\pip-record-r4ds_r_3\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Prjts\dados_financeiros_b3.venv\include\site\python3.10\llvmlite' Check the logs for full command output.

@Prog-LucasAlves thank you for reporting back. The problem is now that llvmlite doesn't yet support Python 3.10. We have a release candidate for a compatible version since last Friday though (0.38.0rc1). In any case you can either:

a) Wait until official Python 3.10 support for llvmlite is released (not before 2022)
b) Use `pip install --pre llvmlite` to get the current release candidare, but beware it's a release candidate so it may still be buggy.

Hope this helps!

PS: I am not sure why `pip` tries to install an older version (0.35 vs 0.37) instead of telling you that `llvmlite` isn't compatible with your version of Python. I presume this may be an issue with `pip`?

**Comment by esc** [comment] 2021-12-01 11:24
@Prog-LucasAlves did this solve the issue for you? Can we close this?

**Closed** 2021-12-01 11:46 UTC
Labels: needtriage

**Comment by esc** [comment] 2021-12-01 11:58
> @Prog-LucasAlves did this solve the issue for you? Can we close this?

Thank you for following up!

**Comment by arnavmehta7** [comment] 2023-02-02 16:55
Hey guys, this isn't working for me. I have python 3.10 but can't install it :\

**Comment by esc** [comment] 2023-02-03 17:24
> Hey guys, this isn't working for me. I have python 3.10 but can't install it :\

Please open a new issue and list:

* What did you try (commands etc..)
* What did you expect?
* What happend instead (error messages, logs, etc..)

We will help you, no worries.
