### ISSUE TITLE
ERROR: Failed building wheel for llvmlite python 3.8.5

### ISSUE THREAD

**Issue by Odianosen25** [numba/llvmlite#625] opened 2020-08-19 17:11 UTC
Hello,

Please I am trying to install numba within my docker container, which uses alpine 3.10 as base image. I get the following errors below:

```
ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-175q8bnc/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-175q8bnc/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-io3m27qx
       cwd: /tmp/pip-install-175q8bnc/llvmlite/
  Complete output (26 lines):
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-175q8bnc/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-175q8bnc/llvmlite/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/lib/python3.8/subprocess.py", line 489, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/tmp/pip-install-175q8bnc/llvmlite/ffi/build.py", line 191, in <module>
      main()
    File "/tmp/pip-install-175q8bnc/llvmlite/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-175q8bnc/llvmlite/ffi/build.py", line 107, in main_posix
      raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/bin/python3' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Successfully built numba
Failed to build llvmlite
DEPRECATION: Could not build wheels for llvmlite which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: llvmlite, numba
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-175q8bnc/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-175q8bnc/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uvl27wez/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/llvmlite
         cwd: /tmp/pip-install-175q8bnc/llvmlite/
    Complete output (29 lines):
    running install
    running build
    got version from file /tmp/pip-install-175q8bnc/llvmlite/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-175q8bnc/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-175q8bnc/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.8/subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-install-175q8bnc/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-175q8bnc/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-175q8bnc/llvmlite/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-175q8bnc/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-175q8bnc/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uvl27wez/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/llvmlite Check the logs for full command output.
```
Any help will be greatly appreciated please.

Regards

**Comment by esc** [comment] 2020-08-19 17:28
@Odianosen25 thanks for asking about this! May I ask what version of `pip` you are using? llvmlite 0.34.0 needs at least `pip` 19.0 for binary wheels to be installed.

**Comment by Odianosen25** [comment] 2020-08-19 18:02
Hello @esc, 

Thanks for the prompt response, my pip version is `20.2.1` as seen from below

```
WARNING: You are using pip version 20.2.1; however, version 20.2.2 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by esc** [comment] 2020-08-19 18:23
@Odianosen25 interesting, do you perhaps have a small dockerfile that I could use to reproduce this? Also, did this work with llvmlite 0.33.0 or are you setting this up now for the first time?

**Comment by esc** [comment] 2020-08-19 18:35
For reference, it seem like your pip isn't picking up the binary wheels for your platform. Which brings me to my next question: what is the architecture of your container?

**Comment by Odianosen25** [comment] 2020-08-19 18:44
> interesting, do you perhaps have a small dockerfile that I could use to reproduce this?

Well I don't but will see if I can quickly put one  together

> Also, did this work with llvmlite 0.33.0 or are you setting this up now for the first time?

Setting up for the first time

> Which brings me to my next question: what is the architecture of your container?

x86-64

**Comment by esc** [comment] 2020-08-19 18:54
@Odianosen25 thanks, I did some online searches and I am getting the impression that our manylinux2010 based llvmlite wheels may not be compatible with Alpine, but I haven't found anything definitive.

**Comment by Odianosen25** [comment] 2020-08-19 18:57
Yes normally manylinux2010 based binaries doesn't install on Alpine, and I tend to build mine myself. So can you lead me to how I can build mine? Then I could try, then try to install again.

Regards

**Comment by esc** [comment] 2020-08-19 18:59
Sure, the installation instructions for compiling llvmlite from source can be found here:

https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#building-manually

Although, I am not sure you can re-use the `llvmdev` conda packges, so you may have to compile LLVM itself from source -- including the Numba/llvmlite specific patches -- yourself. 

Good luck and do let us know how it goes!

**Comment by braxtonmckee** [comment] 2020-08-24 13:38
I also get this failure.

Here's a dockerfile that repro's this for me

```
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y python3  python3-dbg  python3-pip

RUN pip3 install llvmlite==0.34.0
```

**Comment by esc** [comment] 2020-08-24 14:15
@braxtonmckee thanks for reporting this. I ran the Dockerfile locally to obtain the `pip` version number and received this:

```
Step 3/4 : RUN pip3 --version
 ---> Running in 1e9552ec8beb
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```

If you make the following changes to your Dockerfile, the install will likely work:

```
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y python3  python3-dbg  python3-pip

RUN pip3 install -U pip

RUN pip3 install llvmlite==0.34.0
```

**Comment by braxtonmckee** [comment] 2020-08-26 18:55
That seems to do the trick. Thanks @esc

**Comment by gmarkall** [comment] 2020-08-27 09:57
Closing this as the original issue seems to be resolved (manylinux2010 wheels not installable on Alpine Linux). @Odianosen25 if you have some help building yourself using the directions above, it would probably be best to start a thread on the Discourse first: https://numba.discourse.group/ - many thanks!

**Closed by gmarkall** 2020-08-27 09:57 UTC
