### ISSUE TITLE
SVML fails to produce Haswell-friendly code with LLVM 14 patch

### ISSUE THREAD

**Issue by apmasell** [numba/llvmlite#894] opened 2022-12-01 20:23 UTC
The SVML patch for LLVM 14 in #830 fails to produce the correct assembly code on the Haswell architecture. The Haswell chips do not support certain 512-bit instructions, but the SVML optimizer emits them anyway. This was guarded for in https://github.com/numba/llvmlite/blob/main/conda-recipes/llvmdev/numba-3016.ll and several Numba unit tests reference in https://github.com/numba/numba/issues/3016 that also check that illegal instructions are not emitted during SVML optimization.

**Comment by sklam** [comment] 2022-12-01 20:37
ping @Hardcode84. This is the SVML issue we talked about today.

**Comment by stuartarchibald** [comment] 2022-12-02 08:56
With view of making sure everyone is seeing the same thing, any chance you could show the assembly generated from running the test described in `numba-3016.ll` please @apmasell? Thanks!

**Comment by sklam** [comment] 2022-12-02 18:22
We did some more investigation. So `numba-3016.ll` tests are passing. The problem is specifically in numba tests `numba.tests.test_svml` and in testing of `sqrt`; e.g. `numba.tests.test_svml.TestSVMLGeneration.{test_int32_scalar8_fastmath_usecase, test_float64_scalar8_fastmath_usecase, ...}`. All failures are caused by these lines:

https://github.com/numba/numba/blob/94ee0a643c3f7235e627865607efe539b6ccb01e/numba/tests/test_svml.py#L138-L140

It seems like the test were checking that `vsqrtp` instruction should be used instead of SVML calls and the new LLVM14+SVML is generated SVML calls for these cases. Is this a known improvement to SVML and the tests are now outdated?

**Comment by esc** [comment] 2023-06-27 11:31
@sklam what is the status of this. Was it resolved with 0.40.1?

**Closed** 2023-06-27 16:21 UTC
Labels: bug
