### ISSUE TITLE
Wheel support for linux aarch64[arm64]

### ISSUE THREAD

**Issue by odidev** [numba/llvmlite#665] opened 2020-12-09 07:59 UTC
**Summary**
Installing llvmlite on aarch64 via pip using command "pip3 install llvmlite" tries to build wheel from source code

**Problem description**
llvmlite doesn't have wheel for aarch64 on PyPI repository. So, while installing llvmlite via pip on aarch64, pip builds wheel for same resulting in it takes more time to install llvmlite. Making wheel available for aarch64 will benefit aarch64 users by minimizing llvmlite installation time.

**Expected Output**
Pip should be able to download llvmlite wheel from PyPI repository rather than building it from source code.

@llvmlite-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make llvmlite wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by esc** [comment] 2020-12-09 08:53
@odidev thank you for submitting this feature request. Building wheels for `aarch64` requires `manylinux2014` support and IIRC currently we only have `manylinux2010` support. This is on the roadmap for 2021 and we hope to complete this within the next year.

**Comment by hrw** [comment] 2021-02-25 13:10
This will be fun.

manylinux2014 is CentOS 7 based which for aarch64 means llvm:
- 3.9 (epel)
- 5.0 (epel)
- 7.0 (epel and sclo)

While you require llvm 9 or 10. For x86-64 you get llvm 9 in epel.

**Comment by esc** [comment] 2021-02-25 13:14
@hrw that is a great catch! But for the wheels we statically link our own patched version of LLVM into the wheels. So my guess is that that will not matter?

**Comment by hrw** [comment] 2021-02-25 14:15
Some version of LLVM needs to be installed. "pip wheel llvmlite" tries to run "llvm-config".

**Comment by esc** [comment] 2021-02-25 14:16
@hrw yes, but see also: https://numba.discourse.group/t/fixing-filenotfounderror-errno-2-no-such-file-or-directory-llvm-config/510/4

**Comment by hrw** [comment] 2021-02-25 14:19
And when I installed any older one:

``` 
RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '3.4.2'. Be sure to set LLVM_CONFIG to the right executable path.
```

**Comment by hrw** [comment] 2021-02-25 14:21
@esc I have a feeling of 'egg and chicken' situation.

To build binary package please install binary package.

**Comment by esc** [comment] 2021-02-25 14:25
@hrw building from source is documented here: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#building-manually -- `pip install llvmlite` will not work in the majority of cases if `pip` ends up selecting the sdist from PyPi and not the wheels.

**Comment by hrw** [comment] 2021-03-09 13:18
I used quay.io/pypa/manylinux_2_24_aarch64 image and build llvmlite out of the box:

llvmlite-0.37.0.dev0+18.g78fd512.dirty-cp36-cp36m-linux_aarch64.whl
llvmlite-0.37.0.dev0+18.g78fd512.dirty-cp37-cp37m-linux_aarch64.whl
llvmlite-0.37.0.dev0+18.g78fd512.dirty-cp38-cp38-linux_aarch64.whl
llvmlite-0.37.0.dev0+18.g78fd512.dirty-cp39-cp39-linux_aarch64.whl

Would you accept Travis CI job to make them?

**Comment by esc** [comment] 2021-03-09 13:29
@hrw thank you for these.  We disabled Travis a while ago so I'm not sure we could accept those. We currently build our wheels as part of the Anaconda internal build farm and would probably like to include this wheel build there too. However, if you could share some instructions on how to build those wheels -- like a travis-ci configuration to look at -- I would probably adopt those instructions. Also, from what I can tell, we may need to build `armv7l` wheels too?

**Comment by hrw** [comment] 2021-03-09 13:38
I followed your documentation. 

Fetched LLVM source, patched (used quilt):

```
$ mkdir ~/devel/llvmlite
$ cd ~/devel/llvmlite
$ wget https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.1/llvm-10.0.1.src.tar.xz
$ cd llvm-10.0.1.src/
$ quilt import ../llvmlite/conda-recipes/*patch
$ quilt push -a
$ quilt del intel-D47188-svml-VF_LLVM9.patch 
$ quilt push -a
$ quilt del twine_cfg_undefined_behavior.patch 
$ quilt push -a
$ docker run --rm -it -u root -v/home/hrw/devel/llvmlite:/tmp/llvmlite quay.io/pypa/manylinux_2_24_aarch64 bash
```

And then in container:

```
# cd /tmp/llvmlite/llvm-10.0.1.src
# export PREFIX=$PWD/../output CPU_COUNT=16
# ln -sf /usr/bin/python3 /usr/local/bin/python
# chmod 755 ../llvmlite/conda-recipes/llvmdev/build.sh 
# ../llvmlite/conda-recipes/llvmdev/build.sh 
# cd ../llvmlite/
# export PATH=$PWD/../output/bin/:$PATH
# for py in /opt/python/cp3[6789]*;do git clean -dfx ; $py/bin/pip wheel . -w ..;done
```

Simple steps.

**Comment by hrw** [comment] 2021-03-09 13:39
armv7? I could say "does someone still use those?" but some people would find it too harsh.

Anyway there are no manylinux images for 32-bit ARM. So it would be more complicated with probably no users.

**Comment by esc** [comment] 2021-03-09 15:13
@hrw thank you for positing the instructions it is much appreciated! For me personally the noteworthy things are that you bypassed `conda-build` and miniconda entirely  and that you used `pip wheel` to build the wheel. I wasn't aware either of these things are possible. I'm not yet sure how to incorporate this approach (w/o conda build) into our build farm. But it is good to know about the Manylinux2014 docker images and which ones are available.

One question, I saw that you build llvmlite with LLVM 10. The last time I tried this I encountered the following bug, which also means that the Numba maintainers currently build llvmlite with LLVM 9.

The bug is reported here:

https://bugs.llvm.org/show_bug.cgi?id=46996

Can you perhaps check if this is also present in the binaries you compiled?

**Comment by hrw** [comment] 2021-03-09 15:36
OK, So step by step:

1. Neither 'conda-build' nor 'miniconda' were mentioned in [documentation](https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#compiling-llvmlite) you linked. Running 'pip wheel' is simplest form of building wheel file.
2. I used manylinux_2_24_aarch64 image instead of manylinux2014 one as this is where Python world goes now. Should work same in manylinux2014 anyway.
3. Documentation says LLVM 10 so I went with this exact version.

And when it comes to bug:

```
root@d8ec17d139cf:/tmp/llvmpipe# cat simplified.ll 
; ModuleID = 'simplified.ll'
source_filename = "<string>"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "aarch64-linux-gnu"
define [3 x { double, i1 }] @"broken"() local_unnamed_addr #0 {
entry:
    ret [3 x { double, i1 }] zeroinitializer
}

root@d8ec17d139cf:/tmp/llvmpipe# llc -march=aarch64 simplified.ll 
unimplemented reg-to-reg copy
UNREACHABLE executed at /tmp/llvmpipe/llvm-10.0.1.src/lib/Target/AArch64/AArch64InstrInfo.cpp:2818!
Stack dump:
0.      Program arguments: llc -march=aarch64 simplified.ll 
1.      Running pass 'Function Pass Manager' on module 'simplified.ll'.
2.      Running pass 'Post-RA pseudo instruction expansion pass' on function '@broken'
#0 0x0000aaaae4fafe08 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/tmp/llvmpipe/output/bin/llc+0x171fe08)
Aborted (core dumped)
root@d8ec17d139cf:/tmp/llvmpipe# ```

**Comment by hrw** [comment] 2021-03-09 16:21
I build same set of wheels using manylinux2014_aarch64 container. Using same steps.

**Comment by esc** [comment] 2021-03-09 16:36
@hrw thank you for following up.

1) Yes, it is only briefly mentioned above. What is perhaps missing is a section "build using conda-build from scratch".
2) Yes, you have already confirmed this. Thank you!
3) Yes, that aarch64 should use LLVM 9.0 is missing from the docs, this is a bug.

So, it looks like you managed to hit the bug?

**Comment by hrw** [comment] 2021-03-09 16:52
Building with LLVM 9.0.1 went fine as well. Same steps.

When it comes to bug - I just repeated what was in bug. And it does not fail with 9.0.1 version.

**Comment by hrw** [comment] 2021-03-09 17:19
Bug happens same way on LLVM 11.0.1

**Comment by esc** [comment] 2021-03-09 17:21
> Bug happens same way on LLVM 11.0.1

Thank you!! We had wondered if that would happen, good to know that we may have to stay on LLVM 9.0 then for `aarch64`.

**Comment by hrw** [comment] 2021-03-09 17:27
OK. So LLVM 9 will be used.

What about doing releases of aarch64 wheels?

**Comment by esc** [comment] 2021-03-09 17:28
> OK. So LLVM 9 will be used.
> 
> What about doing releases of aarch64 wheels?

Yes, I'll prioritize this now, perhaps we can get those out in time for the 0.36.0 final later on during the week.

**Comment by esc** [comment] 2021-03-11 10:19
Quick status update on this. I have ported the script to our internal build farm,  from the two runs I did so far the first brought our RaspberryPi  to it's knees and we had to send an engineer into the Datacenter to powercycle it. The second one ran overnight, but something went wrong with the process that collects the build log and so it failed and I have no idea why. I need to put this task on hold now because the build farm will be busy for the next few days building the Numba and llvmlite releases but I'll pick this up again as soon as the compute resources required become available again (i.e. next week).

**Comment by hrw** [comment] 2021-03-11 10:22
Building on R/Pi...

That's why I asked about Travis CI.

**Comment by esc** [comment] 2021-03-11 10:35
> Building on R/Pi...
> 
> That's why I asked about Travis CI.

Yes, it may be worth revisiting for sure, I may try to discuss this in the developer meeting, but it will take consensus from the other maintainers before taking this decision. We also have some other hardware that could do this quite quickly but it hasn't been configured to operate as part of the build farm yet.

The main problem with Travis-CI is that the Numba/llvmlite project may no longer qualify since at least some of the maintainers enjoy financial backing and thus we probably  wouldn't obtain free credits (by a recent announcement of Travis-CI). If we have to pay for credits, this introduces an additional layer of beaureurcay to figure out who will pay for the credits and how the money should flow. We are currently in the process of establishing an improved governance model that should make such processes easier, but it will take some time (months) and discusssion until that is in place. Thus for activating Travis-CI we will probably encounter a can of worms of some  politics that must be cleared first. The  other aspect is that Numba/llvmlite is spread across too many CI systems already and  instead of adding yet another one, we feel that it makes more sense to consolidate them. And lastly, the last time we tried building LLVM on public CI we didn't manage because the build kept running into public CI timeouts.

I hope this clarify's our resistance to "simply switch on Travic-CI", which does sound like an enticing option if one isn't aware of the broader context.

**Comment by esc** [comment] 2021-03-15 16:16
Another update on this: unfortunately trying to build this on our internal build farm the build dies very early on with the message `[2021-03-12 11:38:14,188] {docker_operator.py:265} INFO - Error grabbing logs: unexpected EOF` and then the build fails after a few hours w/o producing any artifacts. This means, I don't have an easy way to debug this and the proper thing to do is probably to debug the build farm and figure out what the issue is with the logging. Effectively, this task is now stalled until I have some more time to look into this.

**Comment by hrw** [comment] 2021-03-16 16:38
Would virtual machine as OpenStack instance help?

We may check are there any resources left in Linaro Developer Cloud.

**Comment by esc** [comment] 2021-03-16 16:39
> Would virtual machine as OpenStack instance help?
> 
> We may check are there any resources left in Linaro Developer Cloud.

Thank you for the kind offer. But I think the effort  of hooking up external resources is probably too high.

**Comment by esc** [comment] 2021-03-18 16:31
I updated the software running on our Anaconda internal build farm but the logging error continues to persist. I am out of time on this task for now and it is stalled indefinitely until I have time to revisit it.

**Comment by hrw** [comment] 2021-06-24 07:57
There is also an initiative (WorksOnArm project) under which access to Arm server hardware can be provided at no cost if that helps. You can register a request here: https://github.com/WorksOnArm/cluster

Maybe that will help?

**Comment by esc** [comment] 2021-06-24 08:32
@hrw thank you for the suggestion. The main blocker for this is/was lack off hands. But now that #715 was finally merge yesterday (after two months of work) this issue now stands a good chance of being picked up again. We may look into the cluster you suggested, thank you.

**Comment by esc** [comment] 2021-07-08 19:02
@hrw I have made some progress on this topic at #736 -- I am happy to report some manylinux2014 aarch64 wheels are now available for testing. For more information see:

https://numba.discourse.group/t/numba-0-54-0-rc1-and-llvmlite-v0-37-0-rc1/783/7?u=esc

**Comment by esc** [comment] 2021-07-12 12:19
@hrw the PR at https://github.com/numba/llvmlite/pull/736 is now ready for review, in case you would like to take a look.

**Comment by esc** [comment] 2021-07-16 08:32
@hrw ok, I think with #736 merged that covers aarch64 for raspberry-pi support. What about arm64, by which I assume you mean Apple M1 Silicon?

**Comment by hrw** [comment] 2021-07-16 08:42
AArch64 is proper name of 64-bit Arm architecture. arm64 is popular one.

Thanks for making it happen.

**Comment by esc** [comment] 2021-07-19 11:23
@hrw RC2 wheels are now build and uploaded to PyPi:

https://pypi.org/project/llvmlite/0.37.0rc2/

**Comment by LutzWeischerFujitsu** [comment] 2021-08-17 07:49
'pip3 install llvmlite' works on AArch64, CentOS 8.

**Comment by anton-petrov** [comment] 2021-08-18 09:39
Hi @esc! When 0.37 release is expected?

**Comment by stuartarchibald** [comment] 2021-08-18 09:44
@anton-petrov It's still going through RC testing (on Numba RC3): https://numba.discourse.group/t/numba-0-54-0-rc3/835 I suggest watching the announcements here https://numba.discourse.group/c/announcements/ to get updates, release should be soon (hopefully in the order of a few days, assuming no regressions are reported).

**Comment by sklam** [comment] 2021-08-20 19:00
aarch64 wheels are available: https://pypi.org/project/llvmlite/0.37.0/

**Closed by sklam** 2021-08-20 19:00 UTC
Labels: enhancement

**Comment by esc** [comment] 2021-08-30 09:49
Thank you all!
