### ISSUE TITLE
llvm-config failed executing

### ISSUE THREAD

**Issue by tingyu66** [numba/llvmlite#55] opened 2015-04-21 17:17 UTC
when I tried to install the llvmlite via setup.py, it showed
```
running install
running build
got version from VCS {'version': '0.4.0', 'full': '8a681a2726ae79b640b4147b13cdd5e309a5c74f'}
running build_ext
/usr/local/opt/python/bin/python2.7 ffi/build.py
LLVM version... Traceback (most recent call last):
  File "ffi/build.py", line 112, in <module>
    main()
  File "ffi/build.py", line 106, in main
    main_posix('osx', '.dylib')
  File "ffi/build.py", line 93, in main_posix
    "to the path for llvm-config" % (llvm_config,))
RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
error: command '/usr/local/opt/python/bin/python2.7' failed with exit status 1
```
And I saw from the readme file that **If your LLVM is installed in a non-standard location, first point the LLVM_CONFIG environment variable to the path of the corresponding llvm-config executable.** So how can I find the location of LLVM on my computer? If I find its llvm-config executable, then I should define "LLVM_CONFIG" as the path to the exe, am I right? I'm using OS X Yosemite. Thank you.

**Comment by pitrou** [comment] 2015-04-28 16:26
You could type for example `which llvm-config`.
Regardless, this is not a bug, so I'm closing the issue.

**Closed by pitrou** 2015-04-28 16:26 UTC

**Comment by eusoubrasileiro** [comment] 2015-05-26 23:12
you should have llvm installed that's why

**Comment by chephysics** [comment] 2015-06-19 13:35
If you install llvm via brew (`brew install llvm`), you should probably create the symlinks afterwards by `brew link llvm`

**Comment by keevee09** [comment] 2015-06-26 19:55
Adding to @chephysics comment. This worked for me:
```brew install llvm```
```brew link --force llvm # later brew unlink llvm```
```ln -s /usr/local/Cellar/llvm/3.6.1/include/llvm/Config/llvm-config.h config.h```
llvmlite setup looks for config.h not llvm-congig.h
Then pip install or python setup.py install from source

**Comment by root-11** [comment] 2015-07-05 10:24
...And for Debian/Ubuntu users who run into this problem just install LLVM as:

    sudo apt-get install llvm

**Comment by katastrofa999** [comment] 2017-05-03 14:59
Which version of LLVM is required? LLVM 3.4.2 in Centos 6.x does not have llvm-config:

$ rpm -ql llvm
/usr/bin/bugpoint
/usr/bin/llc
/usr/bin/lli
/usr/bin/lli-child-target
/usr/bin/llvm-ar
/usr/bin/llvm-as
/usr/bin/llvm-bcanalyzer
/usr/bin/llvm-cov
/usr/bin/llvm-diff
/usr/bin/llvm-dis
/usr/bin/llvm-dwarfdump
/usr/bin/llvm-extract
/usr/bin/llvm-link
/usr/bin/llvm-mc
/usr/bin/llvm-mcmarkup
/usr/bin/llvm-nm
/usr/bin/llvm-objdump
/usr/bin/llvm-ranlib
/usr/bin/llvm-readobj
/usr/bin/llvm-rtdyld
/usr/bin/llvm-size
/usr/bin/llvm-stress
/usr/bin/llvm-symbolizer
/usr/bin/llvm-tblgen
/usr/bin/macho-dump
/usr/bin/opt
/usr/share/doc/llvm-3.4.2
/usr/share/doc/llvm-3.4.2/CREDITS.TXT
/usr/share/doc/llvm-3.4.2/LICENSE.TXT
/usr/share/doc/llvm-3.4.2/README.txt
/usr/share/llvm
$

**Comment by seibert** [comment] 2017-05-03 17:09
LLVM 4.0 is required for the latest llvmlite release.

**Comment by ayushman1024** [comment] 2019-01-12 14:59
Just ensure following imports are there( both necessary)

import llvmlite
import llvmlite.binding as llvm

**Comment by serg06** [comment] 2021-01-21 03:05
This worked for me on Centos7 (Amazon Linux 2)

```
sudo yum install clang
```

**Comment by esc** [comment] 2021-01-21 10:12
@serg06 thank you for adding to this. The command you executed probably installed an `llvmdev` package or similar. I.e. the llvmlite setup script `setup.py` was able to find `llvm-config` on the path and thus `llvmlite` could be compiled. 

Though I do have to note, that Numba users may need a custom `llvmdev` package to compile llvmlite since a few patches to LLVM are needed to ensure the correct operation of Numba via llvmlite. You can read more about it here:

https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html
