### ISSUE TITLE
llvmlite-0.27 segfaults win64

### ISSUE THREAD

**Issue by jvesely** [numba/llvmlite#457] opened 2019-01-26 01:47 UTC
Hi,

I've observed that some of our automated tests fail on 64bit python(3.5,3.6,3.7) on windows.
You can see the tests here: https://ci.appveyor.com/project/kmantel/psyneulink/builds/21869697/job/ti1ivglldaopme5o
It looks like uninitialized or NULL pointer dereference (`OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
psyneulink\core\llvm\__init__.py:77: OSError
`).
It might be an error in our scripts, but the same test run ok using llvmlite-0.26 (win64) as well as llvmlite-0.27 on win32, linux and macos.

I don't have a win64 setup other than the appveyor environment, so I can't really investigate further.

**Comment by hassanalinali** [comment] 2019-01-28 15:11
I can confirm the same issue, it throws me a Windows error on 64 bits

**Comment by sklam** [comment] 2019-01-28 20:49
If the error occurs in llvmlite 0.27 and not before, it could be due to an issue with long label names.  A patch for that was merged recently: https://github.com/numba/llvmlite/pull/454.  Can you try testing against the latest llvmlite master?  Pre-built conda packages are available from `conda install -c numba/label/dev llvmlite`.

**Comment by seibert** [comment] 2019-01-28 20:49
We recently worked around a rather strange LLVM 7 bug (#453) that might be the cause of this.  Is there any chance you can switch your test temporarily to use:

```
 conda install -c numba/label/dev llvmlite==0.28.0dev0
```

This fix will appear in our next official release at the end of February, but the above will let you use one of our development packages that already has the fix.

**Comment by jvesely** [comment] 2019-01-29 02:31
Is there no other way to try dev version of llvmlite but conda? dealing with mixing conda and pip in appveyor environment will need more time than I currently have.

**Comment by jvesely** [comment] 2019-01-29 21:12
> If the error occurs in llvmlite 0.27 and not before, it could be due to an issue with long label names. A patch for that was merged recently: #454. Can you try testing against the latest llvmlite master? Pre-built conda packages are available from `conda install -c numba/label/dev llvmlite`.

The issue also does not happen on win32, linux or mac (all using llvmlite-0.27). so it might be something more subtle.

**Comment by stuartarchibald** [comment] 2019-01-29 21:36
When creating the target machine perhaps try setting the relocation model to `'static'`?

**Comment by jvesely** [comment] 2019-02-02 21:38
Hi,
sorry for the delay.
it looks like setting the relocation model to `static` fixes (works around) the problem.
The tests now pass in all tested environments.
Linux+macOS:
https://travis-ci.org/PrincetonUniversity/PsyNeuLink/builds/487938909
win32+win64:
https://ci.appveyor.com/project/jvesely/psyneulink/builds/22079150

**Comment by stuartarchibald** [comment] 2019-02-04 09:38
Glad you got it working. It's not so much a fix/work around as a requirement now imposed by LLVM 7 MCJIT using `ELF` (MCJIT on windows requires ELF http://lists.llvm.org/pipermail/llvm-dev/2013-December/068341.html) . Having tracked this down when moving Numba to use llvmlite based on LLVM 7, this patch https://reviews.llvm.org/D47211 requires the change to `static` relocation, which is fine in a JIT as nothing needs relocating.

**Comment by jvesely** [comment] 2019-02-04 14:10
> Glad you got it working. It's not so much a fix/work around as a requirement now imposed by LLVM 7 MCJIT using `ELF` (MCJIT on windows requires ELF http://lists.llvm.org/pipermail/llvm-dev/2013-December/068341.html) . Having tracked this down when moving Numba to use llvmlite based on LLVM 7, this patch https://reviews.llvm.org/D47211 requires the change to `static` relocation, which is fine in a JIT as nothing needs relocating.


thank you for the explanation. will llvmlite switch to 'static' as default on win64? How is win32 version different that it did not need the change?

**Comment by stuartarchibald** [comment] 2019-02-04 14:30
Also... @jvesely are you happy if we close this as resolved? Thanks.

**Comment by jvesely** [comment] 2019-02-04 17:17
Feel free to close this issue, but it'd be nice to get some notification when the underlying issue is fixed and the defaults work on all platforms.
My expectations were of "working default". I'm not sure if that was correct for the code_model setting.

**Closed** 2019-05-10 16:51 UTC

**Comment by jvesely** [comment] 2019-05-10 17:24
@stuartarchibald, Does it mean the issue is fixed in 0.29?

**Comment by stuartarchibald** [comment] 2019-05-10 17:32
@jvesely please remind me what the underlying issue is? `llvmlite` is a library and so I think it's reasonable for it to support different uses (and defaults are application specific?). Most of the effort for 0.29 has been on LLVM 8 support.

**Comment by jvesely** [comment] 2019-05-10 18:19
> @jvesely please remind me what the underlying issue is? `llvmlite` is a library and so I think it's reasonable for it to support different uses (and defaults are application specific?). Most of the effort for 0.29 has been on LLVM 8 support.

the following code crashes on win64
```
    __cpu_features = binding.get_host_cpu_features().flatten()
    __cpu_name = binding.get_host_cpu_name()

    # Create compilation target, use default triple
    __cpu_target = binding.Target.from_default_triple()
    __cpu_target_machine = __cpu_target.create_target_machine(cpu=__cpu_name, features=__cpu_features, opt=3)
```
I can work around the problem by adding `reloc='static'` as you suggested in https://github.com/numba/llvmlite/issues/457#issuecomment-458716589,
but it'd be nice if ti worked using defualt values i.e. llvmlite picks the right value for the platform instead of the user.

**Comment by jvesely** [comment] 2019-06-02 20:54
The issue is still present in llvmlite-0.29.

**Comment by sklam** [comment] 2019-06-03 13:39
#406 proposes the removal of custom logic for deciding the default for codemodel and relocmodel.  It should help making the default more sensible.  However, a `TargetMachine` can be made for Just-in-time compiling or Ahead-of-time compiling.  It may require an API change to provide the user-intent to pick the right *models.
