### ISSUE TITLE
Error installing llvmlite from pip on fedora

### ISSUE THREAD

**Issue by Carpall** [numba/llvmlite#783] opened 2021-11-01 07:49 UTC
just installed fedora in dual boot, python was already installed.
after trying to install llvmlite package I got this error.
I reinstalled python but it continued to be buggy.
how I fixed: downloaded llvmlite source from release and moving llvmlite folder inside ~/.local/lib/python3.10/site-packages/
```
[carpal@fedora ~]$ sudo pip install llvmlite
[sudo] password for carpal: 
Collecting llvmlite
  Using cached llvmlite-0.35.0.tar.gz (121 kB)
Using legacy 'setup.py install' for llvmlite, since package 'wheel' is not installed.
Installing collected packages: llvmlite
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-auebfsqm/llvmlite_a782a9e25d204fab8666f61a422936de/setup.py'"'"'; __file__='"'"'/tmp/pip-install-auebfsqm/llvmlite_a782a9e25d204fab8666f61a422936de/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2rckp9f_/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.10/llvmlite
         cwd: /tmp/pip-install-auebfsqm/llvmlite_a782a9e25d204fab8666f61a422936de/
    Complete output (29 lines):
    running install
    running build
    got version from file /tmp/pip-install-auebfsqm/llvmlite_a782a9e25d204fab8666f61a422936de/llvmlite/_version.py {'version': '0.35.0', 'full': 'ea23b026930cc00824c907172383f54c9d438e6b'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-auebfsqm/llvmlite_a782a9e25d204fab8666f61a422936de/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-auebfsqm/llvmlite_a782a9e25d204fab8666f61a422936de/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib64/python3.10/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib64/python3.10/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib64/python3.10/subprocess.py", line 966, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib64/python3.10/subprocess.py", line 1842, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-auebfsqm/llvmlite_a782a9e25d204fab8666f61a422936de/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-auebfsqm/llvmlite_a782a9e25d204fab8666f61a422936de/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-auebfsqm/llvmlite_a782a9e25d204fab8666f61a422936de/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-auebfsqm/llvmlite_a782a9e25d204fab8666f61a422936de/setup.py'"'"'; __file__='"'"'/tmp/pip-install-auebfsqm/llvmlite_a782a9e25d204fab8666f61a422936de/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2rckp9f_/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.10/llvmlite Check the logs for full command output.
```

![Screenshot from 2021-11-01 03-46-00](https://user-images.githubusercontent.com/65513900/139639101-6ec90080-1c28-47cb-bd6c-878019f18b1f.png)

**Comment by esc** [comment] 2021-11-01 08:03
@Carpall thank you for reporting this. There are multiple things going wrong here:

a) Installation via `pip` for Python 3.10 is currently not yet supported: https://github.com/numba/llvmlite/pull/769
b) Somehow PyPi gave you llvmlite 0.35 -- but the latest version is 0.37

Also, you can read more about the error message you received here: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip

Hope this helps!

**Comment by esc** [comment] 2021-11-01 08:04
I am closing this as a duplicate of #769 since lack of 3.10 support seems to be the main issue here.

**Closed by esc** 2021-11-01 08:04 UTC
Labels: duplicate
