### ISSUE TITLE
Jetson nano - when import numba -RuntimeError: Unable to find target for this triple (no targets are registered)

### ISSUE THREAD

**Issue by dhgokul** [numba/llvmlite#628] opened 2020-09-01 05:54 UTC
JETSON NANO : When tried to import numba and got below issue. 
RuntimeError: Unable to find target for this triple (no targets are registered)

Kernal report : $ uname -m -p -i -o
**aarch64 aarch64 aarch64 GNU/Linux**

$ file -L `which python`
python: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=d627ef878f18bc969e1914564d7a2c095c310c6d, stripped

cmake command:
 sudo cmake llvm-10.0.1.src/  -DLLVM_TARGETS_TO_BUILD="ARM"  -DLLVM_TARGET_ARCH=ARM -DLLVM_DEFAULT_TARGET_TRIPLE=armv8-linux-gnueabihf  -DLLVM_USE_LINKER=gold -DCMAKE_BUILD_TYPE="Release"

Python version:
>>> import llvmlite
>>> llvmlite.__version__
**'0.34.0'**

Python 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from llvmlite import binding as ll
>>> print(ll.get_process_triple())
**aarch64-unknown-linux-gnu**
>>> print(tuple.__itemsize__)
**8**

Any help appreciated ! Thanks

**Comment by esc** [comment] 2020-09-01 07:32
@dhgokul thanks for asking about this. Without having access to your machine, my guess would be that you need to compile LLVM with the following option to include the target for your architecture:

`-DLLVM_TARGETS_TO_BUILD="ARM;X86;AArch64"` 

Also, please be advised that LLVM may currently be broken in LLVM 10.*  for the `aarch64` target, as reported here:

https://bugs.llvm.org/show_bug.cgi?id=46996

I would suggest to use LLVM 9.* instead.

In fact the current llvmlite release, 0.34.0, is a split dependency release, where all targets except for `aarch64` use LLVM 10.* but `aarch64` uses LLVM 9.*.

**Comment by dhgokul** [comment] 2020-09-01 12:01
@esc Thanks for your prompt response! Will check with LLVM 9 version and get back to you!

**Comment by dhgokul** [comment] 2020-09-09 10:19
@esc Succesfully build llvmlite 9.0 version, but when install numba package i got below error

Collecting numba
  Using cached numba-0.51.2.tar.gz (2.1 MB)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in /usr/local/lib/python3.6/dist-packages (from numba) (0.34.0)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.6/dist-packages (from numba) (1.19.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from numba) (50.3.0)
Building wheels for collected packages: numba
  Building wheel for numba (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sthq7y87/numba/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sthq7y87/numba/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-143d6zug
       cwd: /tmp/pip-install-sthq7y87/numba/
  Complete output (868 lines):
  Using Intel TBB from: /usr
  Using OpenMP from: True
  running bdist_wheel
  running build
  got version from file /tmp/pip-install-sthq7y87/numba/numba/_version.py {'version': '0.51.2', 'full': '9d570961590c09a1eba748c9c37e91d1224fc9ad'}
  running build_py

**Comment by esc** [comment] 2020-09-09 12:28
@dhgokul I don't see any error? Can you perhaps post the complete output?

**Comment by dhgokul** [comment] 2020-09-10 05:29
@esc  Thanks!

PFA - Numba error log :   

[Numba_error_log.txt](https://github.com/numba/llvmlite/files/5199319/Numba_error_log.txt)

root@nvidia:~# uname -m -p -i -o
aarch64 aarch64 aarch64 GNU/Linux

root@nvidia:~# python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import llvmlite
>>> llvmlite.__version__
'0.34.0'

**Machine configuration:** 
nvidia - Jetson nano 
    description: Computer
    product: NVIDIA Jetson Nano Developer [Kit](url)
    serial: 1423019017587
    width: 64 bits
    capabilities: smp cp15_barrier setend swp
  *-core
       description: Motherboard
       physical id: 0
     *-cpu:0
          description: CPU
          product: cpu
          physical id: 0
          bus info: cpu@0
          size: 1132MHz
          capacity: 1479MHz
          capabilities: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpufreq
     *-cpu:1
          description: CPU
          product: cpu
          physical id: 1
          bus info: cpu@1
          size: 1132MHz
          capacity: 1479MHz
          capabilities: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpufreq
     *-cpu:2
          description: CPU
          product: cpu
          physical id: 3
          bus info: cpu@2
          size: 1132MHz
          capacity: 1479MHz
          capabilities: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpufreq
     *-cpu:3
          description: CPU
          product: cpu
          physical id: 4
          bus info: cpu@3
          size: 1132MHz
          capacity: 1479MHz
          capabilities: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpufreq
     *-cpu:4 DISABLED
          description: CPU
          product: idle-states
          physical id: 5
          bus info: cpu@4
     *-cpu:5 DISABLED
          description: CPU
          product: l2-cache
          physical id: 6
          bus info: cpu@5
     *-memory
          description: System memory
          physical id: 7
          size: 3964MiB
     *-pci
          description: PCI bridge
          product: NVIDIA Corporation
          vendor: NVIDIA Corporation
          physical id: 2
          bus info: pci@0000:00:02.0
          version: a1
          width: 32 bits
          clock: 33MHz
          capabilities: pci pm msi ht pciexpress normal_decode bus_master cap_list
          configuration: driver=pcieport
          resources: irq:84 ioport:1000(size=4096) memory:13000000-130fffff
        *-network
             description: Ethernet interface
             product: RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
             vendor: Realtek Semiconductor Co., Ltd.
             physical id: 0
             bus info: pci@0000:01:00.0
             logical name: eth0
             version: 15
             serial: 00:04:4b:eb:c9:d3
             size: 100Mbit/s
             capacity: 1Gbit/s
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi pciexpress msix vpd bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
             configuration: autonegotiation=on broadcast=yes driver=r8168 driverversion=8.045.08-NAPI duplex=full ip=192.168.1.100 latency=0 link=yes multicast=yes port=twisted pair speed=100Mbit/s
             resources: irq:407 ioport:1000(size=256) memory:13004000-13004fff memory:13000000-13003fff
  *-usbhost:0
       product: xHCI Host Controller
       vendor: Linux 4.9.140-tegra xhci-hcd
       physical id: 1
       bus info: usb@1
       logical name: usb1
       version: 4.09
       capabilities: usb-2.00
       configuration: driver=hub slots=5 speed=480Mbit/s
     *-usb
          description: USB hub
          product: 4-Port USB 2.1 Hub
          vendor: Generic
          physical id: 2
          bus info: usb@1:2
          version: 1.01
          capabilities: usb-2.10
          configuration: driver=hub slots=4 speed=480Mbit/s
  *-usbhost:1
       product: xHCI Host Controller
       vendor: Linux 4.9.140-tegra xhci-hcd
       physical id: 2
       bus info: usb@2
       logical name: usb2
       version: 4.09
       capabilities: usb-3.00
       configuration: driver=hub slots=4 speed=5000Mbit/s
     *-usb
          description: USB hub
          product: 4-Port USB 3.1 Hub
          vendor: Generic
          physical id: 1
          bus info: usb@2:1
          version: 1.01
          capabilities: usb-3.10
          configuration: driver=hub slots=4 speed=5000Mbit/s
  *-network:0
       description: Ethernet interface
       physical id: 3
       logical name: rndis0
       serial: 66:56:ba:4e:70:65
       capabilities: ethernet physical
       configuration: broadcast=yes driver=g_ether driverversion=29-May-2008 firmware=tegra-xudc link=yes multicast=yes
  *-network:1
       description: Ethernet interface
       physical id: 4
       logical name: l4tbr0
       serial: 66:56:ba:4e:70:65
       capabilities: ethernet physical
       configuration: broadcast=yes driver=bridge driverversion=2.3 firmware=N/A ip=192.168.55.1 link=yes multicast=yes
  *-network:2 DISABLED
       description: Ethernet interface
       physical id: 5
       logical name: dummy0
       serial: 9a:da:d7:30:22:10
       capabilities: ethernet physical
       configuration: broadcast=yes driver=dummy driverversion=1.0
  *-network:3
       description: Ethernet interface
       physical id: 6
       logical name: usb0
       serial: 66:56:ba:4e:70:67
       capabilities: ethernet physical
       configuration: broadcast=yes driver=g_ether driverversion=29-May-2008 firmware=tegra-xudc link=no multicast=yes

**Comment by esc** [comment] 2020-09-10 09:26
@dhgokul thank you for updating the issue. I had a look at the error log and the following lines seem to be relevant:

```
    building 'numba.np.ufunc.tbbpool' extension
    C compiler: aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

    compile options: '-I/usr/include -I/usr/include/python3.6m -c'
    extra options: '-std=c++11'
    aarch64-linux-gnu-gcc: numba/np/ufunc/gufunc_scheduler.cpp
    aarch64-linux-gnu-gcc: numba/np/ufunc/tbbpool.cpp
    numba/np/ufunc/tbbpool.cpp:30:2: error: #error "TBB version is too old, 2019 update 5, i.e. TBB_INTERFACE_VERSION >= 11005 required"
     #error "TBB version is too old, 2019 update 5, i.e. TBB_INTERFACE_VERSION >= 11005 required"
      ^~~~~
    numba/np/ufunc/tbbpool.cpp: In constructor ‘fix_tls_observer::fix_tls_observer(tbb::interface7::task_arena&, int)’:
    numba/np/ufunc/tbbpool.cpp:89:108: error: no matching function for call to ‘tbb::internal::task_scheduler_observer_v3::task_scheduler_observer_v3(tbb::interface7::task_arena&)’
         fix_tls_observer(tbb::task_arena &arena, int mask) : tbb::task_scheduler_observer(arena), mask_val(mask)
                                                                                                                ^
    In file included from /usr/include/tbb/tbb.h:79:0,
                     from numba/np/ufunc/tbbpool.cpp:15:
    /usr/include/tbb/task_scheduler_observer.h:65:5: note: candidate: tbb::internal::task_scheduler_observer_v3::task_scheduler_observer_v3()
         task_scheduler_observer_v3() : my_proxy(NULL) { my_busy_count.store<relaxed>(0); }
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/tbb/task_scheduler_observer.h:65:5: note:   candidate expects 0 arguments, 1 provided
    /usr/include/tbb/task_scheduler_observer.h:40:7: note: candidate: constexpr tbb::internal::task_scheduler_observer_v3::task_scheduler_observer_v3(const tbb::internal::task_scheduler_observer_v3&)
     class task_scheduler_observer_v3 {
           ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/include/tbb/task_scheduler_observer.h:40:7: note:   no known conversion for argument 1 from ‘tbb::interface7::task_arena’ to ‘const tbb::internal::task_scheduler_observer_v3&’
    error: Command "aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.6m -c numba/np/ufunc/tbbpool.cpp -o build/temp.linux-aarch64-3.6/numba/np/ufunc/tbbpool.o -std=c++11" failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vsyih1qd/numba/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vsyih1qd/numba/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zezbyem0/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/numba Check the logs for full command output.
```

In particular the following might be a good hint:

``` 
    numba/np/ufunc/tbbpool.cpp:30:2: error: #error "TBB version is too old, 2019 update 5, i.e. TBB_INTERFACE_VERSION >= 11005 required"
```

Although I am not yet sure, what to do about it.

**Comment by esc** [comment] 2020-09-10 09:26
@dhgokul FWIW: we do provide pre-compiled  conda packages for both llvmlite and Numba in case that is an option for you. The installation instructions can be found on:

https://numba.readthedocs.io/en/stable/user/installing.html#installing-on-linux-armv8-aarch64-platforms

**Comment by dhgokul** [comment] 2020-09-11 05:48
@esc  Thanks!

**Followed below steps :**
Installed numba from source code and got tbb version issue
git clone git://github.com/numba/numba.git
python3 setup.py install

error: #error "TBB version is too old, 2019 update 5, i.e. TBB_INTERFACE_VERSION >= 11005 required"

Numba error log:  
[numba_source_error.txt](https://github.com/numba/llvmlite/files/5206915/numba_source_error.txt)


Successfully installed tbb latest version using below steps
git clone https://github.com/wjakob/tbb.git
cd tbb/build
cmake ..
make -j
sudo make install

TBB installed log : 
[tbb_install_log.txt](https://github.com/numba/llvmlite/files/5206917/tbb_install_log.txt)

Then recompile numba using below cmd and successfully installed numba
python3 setup.py install

Numba Build log:
[Numba_build_log.txt](https://github.com/numba/llvmlite/files/5206924/Numba_build_log.txt)


When import numba package and got this issue	
root@nvidia:~/numba# python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import  numba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/numba/numba/__init__.py", line 215, in <module>
    import numba.typed
  File "/root/numba/numba/typed/__init__.py", line 1, in <module>
    from .typeddict import Dict
  File "/root/numba/numba/typed/typeddict.py", line 22, in <module>
    @njit
  File "/root/numba/numba/core/decorators.py", line 257, in njit
    return jit(*args, **kws)
  File "/root/numba/numba/core/decorators.py", line 180, in jit
    return wrapper(pyfunc)
  File "/root/numba/numba/core/decorators.py", line 209, in wrapper
    **dispatcher_args)
  File "/root/numba/numba/core/dispatcher.py", line 707, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/root/numba/numba/core/registry.py", line 47, in target_context
    return self._toplevel_target_context
  File "/root/numba/numba/core/utils.py", line 349, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/numba/numba/core/registry.py", line 31, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/root/numba/numba/core/base.py", line 259, in __init__
    self.init()
  File "/root/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/root/numba/numba/core/cpu.py", line 47, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/root/numba/numba/core/codegen.py", line 645, in __init__
    self._init(self._llvm_module)
  File "/root/numba/numba/core/codegen.py", line 650, in _init
    target = ll.Target.from_triple(ll.get_process_triple())
  File "/usr/local/lib/python3.6/dist-packages/llvmlite/binding/targets.py", line 197, in from_triple
    raise RuntimeError(str(outerr))
RuntimeError: No available targets are compatible with triple "aarch64-unknown-linux-gnu"

**Comment by esc** [comment] 2020-09-11 05:59
@dhgokul this looks like you didn't include the correct targets when compiling LLVM? How did you compile it? My guess ia that you need to add `-DLLVM_TARGETS_TO_BUILD="host;ARM;X86;AArch64"` or something similar to the `cmake` call to enable the `aarch64` target.

**Comment by dhgokul** [comment] 2020-09-11 08:04
@esc We complied llvm 9.0 using below cmake command

sudo cmake ../ -DLLVM_TARGETS_TO_BUILD="ARM;X86;AArch64" -DLLVM_TARGET_ARCH=ARM -DLLVM_DEFAULT_TARGET_TRIPLE=armv8-linux-gnueabihf -DLLVM_USE_LINKER=gold -DCMAKE_BUILD_TYPE="Release"

**Comment by esc** [comment] 2020-09-11 09:39
@dhgokul I am not sure what the issue is, so I will have to guess. Maybe the error is due to the lines `-DLLVM_TARGET_ARCH=ARM -DLLVM_DEFAULT_TARGET_TRIPLE=armv8-linux-gnueabihf`. I  don't know kind of effect they will have. Did you follow some online instructions for this? I usually compile LLVM with the following options: `-DLLVM_TARGETS_TO_BUILD="host;ARM;X86;AArch64" -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_BUILD_TYPE=RELEASE` --  perhaps you can try that?

**Comment by dhgokul** [comment] 2020-09-11 09:51
@esc  Thanks! will check and update you

**Comment by dhgokul** [comment] 2020-09-13 14:22
@esc I tried with below cmake command and installed llvm and numba. Still facing same error when import numba package

![image](https://user-images.githubusercontent.com/5689804/93020421-8ded7500-f5fa-11ea-98f7-4a2d5a9d6940.png)

**Comment by esc** [comment] 2020-09-14 13:13
@dhgokul judging from the logs, LLVM build seems to be OK, so our guess here is that llvmlite may not be compiled correctly, since the LLVM it is using doesn't seem to have support for the architecture in question.

It's not immediately apparent, what is going on here. We would suggest to check the following things:

* Did you rebuild llvmlite? This is always required after rebuild LLVM.
* Did you make sure that you uninstalled any previous versions of llvmlite? Depending on where you are installing things and how, (pip, conda, setuptools, etc) there may be some junk leftover that is confusing.
* Did you set the `LLVM_CONFIG=...` variable correctly when building llvmlite?

**Comment by esc** [comment] 2020-09-17 08:36
@dhgokul just following up on this one, have you managed to make any progress? Is there anything else I can suggest to move forward?

**Comment by dhgokul** [comment] 2020-09-21 07:51
@esc  Thanks! will check above steps and let u know

**Comment by esc** [comment] 2020-09-21 08:40
@dhgokul use of `LLVM_CONFIG`  is documented in step 2 here:

https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#compiling-llvmlite

Basically, after you compile LLVM itself, you need to compile `llvmlite` and in order to do so, you need to tell llvmlite where to find  the compiled LLVM. Makes sense?

**Comment by dhgokul** [comment] 2020-09-22 10:32
@esc After compile with LLVM_CONFIG . I got same issue.

root@user:~# LLVM_CONFIG=/usr/local/bin/llvm-config CXXFLAGS=-fPIC pip3 install llvmlite
Processing ./.cache/pip/wheels/be/45/f2/317d332a8293efdad76842688648c139b7c52b66eab68e2727/llvmlite-0.34.0-cp36-cp36m-linux_aarch64.whl
Installing collected packages: llvmlite
Successfully installed llvmlite-0.34.0
root@user:~# echo $LLVM_CONFIG
/root/llvm-9.0.1.src/llvm_build_dir/bin/llvm-config
root@user:~# python3
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/numba/__init__.py", line 213, in <module>
    import numba.typed
  File "/usr/local/lib/python3.6/dist-packages/numba/typed/__init__.py", line 1, in <module>
    from .typeddict import Dict
  File "/usr/local/lib/python3.6/dist-packages/numba/typed/typeddict.py", line 22, in <module>
    @njit
  File "/usr/local/lib/python3.6/dist-packages/numba/core/decorators.py", line 257, in njit
    return jit(*args, **kws)
  File "/usr/local/lib/python3.6/dist-packages/numba/core/decorators.py", line 180, in jit
    return wrapper(pyfunc)
  File "/usr/local/lib/python3.6/dist-packages/numba/core/decorators.py", line 209, in wrapper
    **dispatcher_args)
  File "/usr/local/lib/python3.6/dist-packages/numba/core/dispatcher.py", line 708, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/usr/local/lib/python3.6/dist-packages/numba/core/registry.py", line 47, in target_context
    return self._toplevel_target_context
  File "/usr/local/lib/python3.6/dist-packages/numba/core/utils.py", line 349, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/dist-packages/numba/core/registry.py", line 31, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/usr/local/lib/python3.6/dist-packages/numba/core/base.py", line 259, in __init__
    self.init()
  File "/usr/local/lib/python3.6/dist-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/numba/core/cpu.py", line 47, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/usr/local/lib/python3.6/dist-packages/numba/core/codegen.py", line 645, in __init__
    self._init(self._llvm_module)
  File "/usr/local/lib/python3.6/dist-packages/numba/core/codegen.py", line 650, in _init
    target = ll.Target.from_triple(ll.get_process_triple())
  File "/usr/local/lib/python3.6/dist-packages/llvmlite/binding/targets.py", line 197, in from_triple
    raise RuntimeError(str(outerr))
RuntimeError: No available targets are compatible with triple "aarch64-unknown-linux-gnu"
>>>

**Comment by esc** [comment] 2020-09-22 12:56
Judging from the line:

```
Processing ./.cache/pip/wheels/be/45/f2/317d332a8293efdad76842688648c139b7c52b66eab68e2727/llvmlite-0.34.0-cp36-cp36m-linux_aarch64.whl
```

it seems that pip is reusing a cached wheel instead compiling `llvmlite`  again. This means no re-compile is taking place and you are using an older version of llvmlite. Perhaps you need to somehow clear your `pip` cache? Or maybe use `--no-cache-dir` to disable `pip`  from accessing it's cache?

**Comment by dhgokul** [comment] 2020-09-24 08:38
Many thanks! @esc 
After lot of struggle installed numba and llvmlite in jetson nano board.   :) 
LLVM_CONFIG=/usr/local/bin/llvm-config CXXFLAGS=-fPIC pip3 --no-cache-dir install llvmlite

Will let you know if we are facing any other issue

**Comment by esc** [comment] 2020-09-24 09:41
@dhgokul I am SO happy this finally worked for you. Congrats! I'll close this issue now and please feel free to open a new one in case you hit any more snags. Thanks for remaining persistent and thanks for using Numba!

**Closed by esc** 2020-09-24 09:41 UTC
Labels: build, help wanted
