### ISSUE TITLE
manylinux1: Could not load shared object file: libllvmlite.so

### ISSUE THREAD

**Issue by pavlin-policar** [numba/llvmlite#498] opened 2019-07-06 10:52 UTC
I apologize if this is the wrong place to post this, but I'm kind of at a loss of where I could get any help with my issue.

I've set up CI on azure pipelines in order to build my package wheels on every platform, so they're easily publishable to PyPI. My package depends on numba, and hence, llvmlite. For linux, I use the manylinux1 docker image to get the appropriate wheels. I am able to build the wheels all right, with no issues. Then, I'd like to verify that the wheels are ok, so I install the built manylinux wheel using pip and run the tests using pytest. All of this happens inside the same docker container, but that shouldn't be an issue. When I run my tests, however, I get the following error:

```
tests/test_nearest_neighbors.py:6: in <module>
    import pynndescent
/home/vsts_azpcontainer/.local/lib/python3.6/site-packages/pynndescent/__init__.py:2: in <module>
    import numba
/home/vsts_azpcontainer/.local/lib/python3.6/site-packages/numba/__init__.py:11: in <module>
    from . import config, errors, _runtests as runtests, types
/home/vsts_azpcontainer/.local/lib/python3.6/site-packages/numba/config.py:18: in <module>
    import llvmlite.binding as ll
/home/vsts_azpcontainer/.local/lib/python3.6/site-packages/llvmlite/binding/__init__.py:6: in <module>
    from .dylib import *
/home/vsts_azpcontainer/.local/lib/python3.6/site-packages/llvmlite/binding/dylib.py:4: in <module>
    from . import ffi
/home/vsts_azpcontainer/.local/lib/python3.6/site-packages/llvmlite/binding/ffi.py:154: in <module>
    raise OSError("Could not load shared object file: {}".format(_lib_name))
E   OSError: Could not load shared object file: libllvmlite.so
```

This is very puzzling to me. From my understanding of Python wheels, everything should be bundled together so it's instantly runnable once installed. However, the error seems to indicate that the shared object file is missing. I've also checked what's actually being installed, and it seems to be the right wheel:

```
Collecting llvmlite>=0.29.0 (from numba>=0.39->pynndescent>=0.3->openTSNE==0.3.8)
Downloading https://files.pythonhosted.org/packages/09/f1/4fa99c2079132da8694361fb9a19094616f1ba2c2eae610379e75394575f/llvmlite-0.29.0-cp36-cp36m-manylinux1_x86_64.whl (20.4MB)
```

If it helps, [here's](https://dev.azure.com/pavlingp/openTSNE/_build/results?buildId=104) the link to the azure pipeline logs and the corresponding [configuration file](https://github.com/pavlin-policar/openTSNE/blob/azure-pipelines/azure-pipelines.yml).

I realise this is probably asking much, so you're welcome to close this if it's too far out there, but I'd appreciate it if you could at least point me in the right direction.

**Comment by esc** [comment] 2019-07-06 18:47
@pavlin-policar thanks for reporting this and rest assured that you have come to the right place. I will label this as `needtriage` for the time being since it will probably require some effort to reproduce. And thank you for helping to improve Numba and llvmlite!

**Comment by sklam** [comment] 2019-08-02 14:19
I can reproduce this bug.  The wheels may have been built with the wrong ABI setting.

**Comment by sklam** [comment] 2019-08-02 14:20
But, it's odd that `auditwheel` think that the wheels are fine.

**Comment by sklam** [comment] 2019-08-02 18:29
I've uploaded new wheels to pypi with build-number=1.  

Closing.

**Closed by sklam** 2019-08-02 18:29 UTC
Labels: needtriage

**Comment by pavlin-policar** [comment] 2019-08-03 08:20
It seems to work now, thanks!

**Comment by vishakraj25** [comment] 2019-12-15 03:20
Hello,

I have the same issue with numba cannot load libllvmlit.so 

How to resolve this
Thanks

**Comment by esc** [comment] 2019-12-16 12:37
@vishakraj25 thanks for reporting this, could you please list, which operating system you are on, which Numba version you are using and how you installed it. Thanks!

**Comment by vishakraj25** [comment] 2019-12-16 15:25
I have Pydroid app in Android and installed using the command "easy_install  librosa".
Got installed. But when importing librosa makes the issue and thanks for helping me.

**Comment by esc** [comment] 2019-12-16 16:10
@vishakraj25 I am not sure that Numba will be supported on Android, but @seibert probably 
knows more.

**Comment by seibert** [comment] 2019-12-16 16:12
We haven't tried making Numba work on Android yet, since there are so many variations.  However, it is good for us to know that people are trying to use it.  We don't have a workaround for this currently.

**Comment by vishakraj25** [comment] 2019-12-16 16:26
Sounds adding Numba on Android in future, thanks

**Comment by laleye** [comment] 2022-09-24 19:51
Hello,

I have the same issue with numba... This is the error I got:


OSError: Could not load shared object file: libllvmlite.so
Errors were: [OSError('python3.7/site-packages/llvmlite/binding/libllvmlite.so: undefined symbol: _ZN4llvm16JITEventListener27createIntelJITEventListenerEv, version LLVM_11'), OSError('libllvmlite.so: cannot open shared object file: No such file or directory'), OSError('./libllvmlite.so: cannot open shared object file: No such file or directory'), OSError(python3.7/site-packages/llvmlite/binding/libllvmlite.so: undefined symbol: _ZN4llvm16JITEventListener27createIntelJITEventListenerEv, version LLVM_11')]

Packges:
-----------

numba-0.48.0
llvmlite 0.31.0

How to resolve this
Thanks
